# Generated by Django 4.1.2 on 2022-11-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="shawon_p1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.IntegerField(max_length=20)),
                ("customer_name", models.CharField(max_length=20)),
                ("org", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("nid", models.IntegerField(max_length=20)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
    ]
