# Generated by Django 4.1.2 on 2022-11-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_info", "0002_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("password", models.CharField(max_length=20)),
            ],
        ),
    ]
