# Generated by Django 4.1.2 on 2022-11-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_info", "0003_info"),
    ]

    operations = [
        migrations.DeleteModel(name="info",),
        migrations.DeleteModel(name="room",),
        migrations.DeleteModel(name="shawon_p1",),
    ]
