# Generated by Django 4.1.2 on 2022-11-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("my_info", "0004_delete_info_delete_room_delete_shawon_p1"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=1000)),
            ],
        ),
    ]
