# Generated by Django 4.1.2 on 2022-11-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_info", "0008_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pname", models.CharField(max_length=50)),
                ("pd", models.CharField(max_length=50)),
                ("ddate", models.DateField()),
                ("quantity", models.IntegerField()),
                ("contactno", models.IntegerField()),
                ("dtime", models.TimeField()),
                ("dcity", models.CharField(max_length=50)),
                ("dadd", models.CharField(max_length=50)),
                ("bloodg", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(model_name="appointment", name="dept",),
    ]
