# Generated by Django 4.1.2 on 2022-11-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_info", "0010_ambulance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blooddonor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("bgroup", models.CharField(max_length=50)),
                ("ldate", models.DateField()),
                ("quantity", models.IntegerField()),
                ("contactno", models.IntegerField()),
                ("age", models.IntegerField()),
                ("city", models.CharField(max_length=50)),
                ("add", models.CharField(max_length=50)),
            ],
        ),
    ]
