# Generated by Django 4.1.2 on 2022-11-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_info", "0011_blooddonor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ambulance",
            name="contactno",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ambulance",
            name="dadd",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ambulance", name="dep", field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="ambulance", name="dtime", field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="ambulance", name="nop", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="ambulance",
            name="oxygen",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ambulance",
            name="source",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ambulance",
            name="to",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="ambulance",
            name="type",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="email",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="gender",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="phoneno",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="pname",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="problem",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="blood",
            name="bloodg",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="blood", name="contactno", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="blood",
            name="dadd",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="blood",
            name="dcity",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="blood", name="ddate", field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="blood", name="dtime", field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="blood",
            name="pd",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="blood",
            name="pname",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="blood", name="quantity", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="blooddonor",
            name="add",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="blooddonor", name="age", field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="blooddonor",
            name="bgroup",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="blooddonor",
            name="city",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="blooddonor",
            name="contactno",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="blooddonor", name="ldate", field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="blooddonor",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="blooddonor",
            name="quantity",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="login",
            name="password",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="login",
            name="username",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="signup",
            name="email",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="signup",
            name="password",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="signup",
            name="username",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
