# Generated by Django 4.1.2 on 2022-11-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_info", "0012_alter_ambulance_contactno_alter_ambulance_dadd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blood",
            name="bloodg",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
