# Generated by Django 4.1.2 on 2022-11-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_info", "0013_alter_blood_bloodg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="email",
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="contactus",
            name="email",
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="signup",
            name="email",
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
