# Generated by Django 4.1.2 on 2022-11-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_info", "0015_appointment_dept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blood",
            name="bloodg",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
